language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

env:
  - SYMFONY_VERSION="2.6.*"

matrix:
  allow_failures:
    - php: nightly
  fast_finish: false
  include:
    - php: 5.6

before_script:
  - composer selfupdate
  - composer require symfony/symfony:${SYMFONY_VERSION}

script:
  - phpunit -c app/
