# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

## Our services
services:
  article_parser:
    class: AppBundle\Service\ArticleParser
    arguments:
      - "%article_parser_hostname%"
      - "%article_parser_encoding_type%"
      - "%article_parser_username%"
      - "%article_parser_password%"
  user.registration.form.type:
    class: AppBundle\Form\Type\RegistrationFormType
    tags:
      - { name: form.type, alias: app_user_registration }
  user.profile.edit.type:
    class: AppBundle\Form\Type\ProfileEditFormType
    tags:
      - { name: form.type, alias: app_user_profile }
  user.registration.completed:
    class: AppBundle\EventListener\RegistrationListener
    arguments: [@router]
    tags:
      - { name: kernel.event_subscriber }
